# Site settings
title: Joshinkan Werder e.V.

author: Sven Mischkewitz
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://joshinkan.de" # the base hostname & protocol for your site

# Build settings
source: src
destination: public
exclude:
  - bower_components
sass:
  sass_dir: _sass
  style: :compressed
  sourcemaps: :auto
markdown: kramdown

# Plugins
gems:
  - jekyll-redirect-from
